//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Process
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Task
	{
		protected virtual void Run()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Validate()
		{
			throw new System.NotImplementedException();
		}

		public virtual int Execute()
		{
			throw new System.NotImplementedException();
		}

	}
}

