//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Dobbelaar.Domain;

namespace Process
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Task
	{
        private Dobbelsteen _dobbelsteen = new Dobbelsteen();

		protected virtual int Run()
		{
			return _dobbelsteen.Gooi();
		}

		protected virtual bool Validate()
		{
		    return true; // GOEDDD
		}

		public virtual int Execute()
		{
            if(!Validate()) throw new Exception("Mag niet.");

		    return Run();
		}

	}
}

