//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interface
{
	using Interface.Views;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MainWindow
	{
		public virtual Dots Dots
		{
			get;
			set;
		}

		public virtual Text Text
		{
			get;
			set;
		}

		public virtual Photo Photo
		{
			get;
			set;
		}

		public virtual Control Control
		{
			get;
			set;
		}

	}
}

