//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Process;

namespace Interface
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Control
	{
	    private Task _task = new Task();

	    public virtual int Gooi()
	    {
	        return _task.Execute();
	    }
	}
}